MUSIC =

MUSIC_LIB = -L. -L/lib -L/opt/4if-LS/arm-none-eabi-gcc/arm-none-eabi/lib -L/opt/4if-LS/arm-none-eabi-gcc/lib/gcc/arm-none-eabi/4.7.1 -lmusic -lm -lgcc -lc
MUSIC_INCLUDES = -Iaudio-hw
MUSIC_CC = -std=c99 -nostartfiles
MUSIC_QUEMU = -soundhw all

include ../common_app.mk
